# What is Torch?
Torch is an open-source machine learning library, a scientific computing framework, and a scripting language based on Lua

# what is PyTorch?
PyTorch offers domain-specific libraries such as TorchText, TorchVision, and TorchAudio, all of which include datasets.

# TENSORS
Tensors are a specialized data structure that are very similar to arrays and matrices. Tensors can run on GPUs or other hardware accelerators. Tensors are also optimized for automatic differentiation 


In [2]:
import torch
import numpy as np

ModuleNotFoundError: No module named 'torch'

In [8]:
# direct tensors
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [9]:
# tensor from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data i.e. its shape
print(f"Ones Tensor: \n {x_ones} \n")


# Returns a tensor with the same size as input that is filled with random numbers
# from a uniform distribution on the interval [0,1).

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7014, 0.8271],
        [0.7536, 0.8763]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4771, 0.8117, 0.8949],
        [0.2307, 0.4574, 0.2820]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor operations

In [12]:
tensor_a = torch.tensor([1, 2, 3, 4])

In [14]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

# Element-wise addition
result = tensor_a + tensor_b

print(result)

tensor([ 6,  8, 10, 12])


In [15]:
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
result = torch.mm(matrix_a, matrix_b)

print(result)

tensor([[19, 22],
        [43, 50]])


In [16]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

# Element-wise multiplication
result = tensor_a * tensor_b

print(result)

tensor([ 5, 12, 21, 32])


In [17]:
matrix = torch.tensor([[1, 2], [3, 4]])

# Transposing the matrix
transposed_matrix = matrix.t()

In [20]:
tensor = torch.tensor([[1, 2], [3, 4]])

# Summing along a specified axis
sum_along_axis_1 = tensor.sum(dim=1)

print(sum_along_axis_1)

tensor([3, 7])


In [21]:
tensor = torch.tensor([1, 2, 3, 4, 5])

# Slicing the tensor
sliced_tensor = tensor[1:4]

In [22]:
tensor = torch.tensor([[1, 2], [3, 4]])

# Computing the sum along all dimensions
total_sum = tensor.sum()

print(total_sum)

tensor(10)


In [24]:
tensor = torch.tensor([1.0, 2.0, 3.0])

# Element-wise exponential
exponential_tensor = torch.exp(tensor)

print(exponential_tensor)

tensor([ 2.7183,  7.3891, 20.0855])


# Quickstart

In [2]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [4]:
# Every TorchVision Dataset includes two arguments: transform and target_transform 
# to modify the samples and labels respectively.

# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",                      # Root directory of dataset
    train=True,                       # If True, creates dataset from train-images
    download=True,                    # If True, downloads the dataset from the internet and puts it in root directory
    transform=ToTensor(),             # A function/transform that takes in an PIL image and returns a transformed version
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

100%|██████████| 26421880/26421880 [00:00<00:00, 116186421.15it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 4679097.50it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 59374678.22it/s]

Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw


100%|██████████| 5148/5148 [00:00<00:00, 8029853.85it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [5]:
# number of training examples utilized in one iteration.
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [25]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        # applies the sequence of linear layers and activation 
        # functions to the flattened input, producing the raw output scores (logits) for each class.
        return logits

model = NeuralNetwork().to(device) 
# An instance of the NeuralNetwork class is created.
# .to(device) moves the model to a specified device (e.g., CPU or GPU) for computation.
print(model)

Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [26]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [27]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset) # stores the total number of samples in the training dataset.
    model.train() # sets the model in training mode
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # forward pass and loss computation
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()   # computes the gradients of the model parameters with respect to the loss
        optimizer.step()  # updates the model parameters using the gradients computed during backpropagation
        optimizer.zero_grad() # resets the gradients to zero after each batch

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [28]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [29]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.303779  [   64/60000]
loss: 2.291703  [ 6464/60000]
loss: 2.277188  [12864/60000]
loss: 2.262796  [19264/60000]
loss: 2.260150  [25664/60000]
loss: 2.223715  [32064/60000]
loss: 2.234977  [38464/60000]
loss: 2.198499  [44864/60000]
loss: 2.199868  [51264/60000]
loss: 2.175485  [57664/60000]
Test Error: 
 Accuracy: 32.1%, Avg loss: 2.166260 

Epoch 2
-------------------------------
loss: 2.175121  [   64/60000]
loss: 2.166471  [ 6464/60000]
loss: 2.116611  [12864/60000]
loss: 2.128655  [19264/60000]
loss: 2.087241  [25664/60000]
loss: 2.023089  [32064/60000]
loss: 2.053546  [38464/60000]
loss: 1.975482  [44864/60000]
loss: 1.990534  [51264/60000]
loss: 1.924655  [57664/60000]
Test Error: 
 Accuracy: 57.7%, Avg loss: 1.918854 

Epoch 3
-------------------------------
loss: 1.941259  [   64/60000]
loss: 1.919423  [ 6464/60000]
loss: 1.815124  [12864/60000]
loss: 1.853860  [19264/60000]
loss: 1.751615  [25664/60000]
loss: 1.691894  [32064/600

In [30]:
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth
